### ISSUE TITLE
Carbon balance error with logging

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates#1416]
### Describe the issue

I am running a single site simulation where I want to clear cut the forest using the logging module.  I'm restarting from a previous run, and trying to clear cut on the first  day of the  new simulation.  My logging  parameters started out: 
fates_landuse_logging_coll_under_frac = 0 ;
 fates_landuse_logging_collateral_frac = 0 ;
 fates_landuse_logging_dbhmax = 10000 ;
 fates_landuse_logging_dbhmax_infra = 35 ;
 fates_landuse_logging_dbhmin = 1 ;
 fates_landuse_logging_direct_frac = 1.0 ;
 fates_landuse_logging_event_code = 19500101 ;
 fates_landuse_logging_export_frac = 1 ;
 fates_landuse_logging_mechanical_frac = 0 ;

But I get an error in the EcosystemBalanceCheckMod.
I tried setting direct_frac to lower numbers but I trigger the same error (different numbers) even  with  direct_frac=0.25. 

### Relevant log output

```shell
Logging Event Enacted on date: 01-01-1950                                                                                                  
 FATES dynamics complete                                                                                                                   
 --WARNING-- skipping CN balance check for first timestep                                                                                  
    Completed timestep: 1950-01-01_00:30:00                                                                                                
 Beginning timestep   : 1950-01-01_01:00:00                                                                                                
 column cbalance error =   -139.50590790885786                1                                                                            
 Latdeg,Londeg         =    41.062500000000000       -78.687500000000000                                                                   
 input                 =    1.1866876844385662E-002                                                                                        
 output                =    1.3828182244300105E-003                                                                                        
 er                    =    1.3828182244300105E-003   1.3828182244300105E-003                                                              
 fire                  =    0.0000000000000000                                                                                             
 hrv_to_atm            =    0.0000000000000000                                                                                             
 leach                 =    0.0000000000000000                                                                                             
 begcb                 =    15189.475106525939                                                                                             
 endcb                 =    15328.991498493417        14695.982962670099                                                                   
 totsomc               =    14695.982962670099                                                                                             
 delta store           =    139.51639196747783                                                                                             
 ENDRUN:ERROR in /global/u2/j/jneedham/E3SM-mrv/components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90 at line 319
```

### FATES tag

sci.1.82.6_api.39.0.0-9-gea425ee7

### Host land model tag

v3.0.0-5362-ga435e8dd8c

### Machine

perlmutter

**Comment by ckoven** [comment]
Hi @JessicaNeedham I think this is something I ran into and fixed via these changes to [EcosystemBalanceCheckMod.F90](https://github.com/E3SM-Project/E3SM/pull/7231/files#diff-f888e1b9524ef8e96ea177d7d09a0b682086d36fa3b1b45256f2a4252d04f7b4) in PR https://github.com/E3SM-Project/E3SM/pull/7231?

**Comment by JessicaNeedham** [comment]
@ckoven what are the corresponding FATES branches? I see the PR #1382 but that doesn't seem  to have all the variables - I'm still getting an error about a missing filter_vegzen_pa.

**Comment by ckoven** [comment]
that should have all the needed stuff, so that E3SM PR must be on a branch that has other things. You might just want to take only the changes that are in `EcosystemBalanceCheckMod.F90`. I think if you cherry-pick commit https://github.com/E3SM-Project/E3SM/commit/663970136c3a075ebb9c5835aaf161993fd19e59 that should work?
